[package]
name = "cliws"
version = "0.1.0"
authors = ["b23r0 <b23r0@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.2"
signal-hook = "0.3.10"
nix = "0.23.0"
atty = "0.2"
ioctl-rs = "0.2"