[package]
name = "cliws"
version = "0.1.0"
authors = ["b23r0 <b23r0@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.2"
sl-console = { git = "https://github.com/sl-sh-dev/sl-console.git" }